import os
from openai import OpenAI
import time

class TraceGenerator:
    def __init__(self, api_key=None, model="gpt-4o"):
        self.client = OpenAI(api_key=api_key or os.environ.get("OPENAI_API_KEY"))
        self.model = model

    def generate(self, problem_desc: str, code: str) -> str:
        """
        Generates a Chain-of-Thought explanation for the given code.
        """
        system_prompt = (
            "You are an expert algorithmist explaining a Python solution for a "
            "combinatorial optimization problem (SDS). The solution was generated by "
            "an evolutionary algorithm. Your goal is to write a thinking trace that "
            "rationalizes the strategy used in the code (e.g., sorting keys, greedy logic, "
            "constraint checking). Do NOT explain line-by-line syntax. Explain the STRATEGY "
            "and reasoning behind the approach. Output ONLY the content of the thinking trace, "
            "without any XML tags or markdown formatting."
        )
        
        user_prompt = f"PROBLEM:\n{problem_desc}\n\nCODE:\n{code}\n\nExplain the reasoning:"
        
        for _ in range(3): # Retry logic
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    temperature=0.3
                )
                return response.choices[0].message.content
            except Exception as e:
                print(f"OpenAI Error: {e}. Retrying...")
                time.sleep(2)
        
        return "Analysis failed."